myName = input("What's your name? ")
myAge = input("How old are you? ")
Food = input("What's your favorite food? ")
Music = input("What's your favorite music? ")
Live = input("Where do you live? ")

print()
print("you are")
print(myName)
print()

print("and are the ripe old age of")
print(myAge)
print()
print("You're probably hungry for ")
print(Food)
print()
print("You're probably listening to")
print(Music)
print()
print("You're probably living in the amazing")
print(Live)
